// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbAlimentacion
    {
        public tbAlimentacion()
        {
            tbAnimales = new HashSet<tbAnimales>();
        }

        public int alim_Id { get; set; }
        public string alim_Descripcion { get; set; }
        public int? alim_UserCreacion { get; set; }
        public DateTime? alim_FechaCreacion { get; set; }
        public int? alim_UserModificacion { get; set; }
        public DateTime? alim_FechaModificacion { get; set; }
        public bool? alim_Estado { get; set; }

        public virtual tbUsuarios alim_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios alim_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbAnimales> tbAnimales { get; set; }
    }
}