// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbAreasZoologico
    {
        public tbAreasZoologico()
        {
            tbAnimales = new HashSet<tbAnimales>();
        }

        public int arzo_Id { get; set; }
        public string arzo_Descripcion { get; set; }
        public int? arzo_UserCreacion { get; set; }
        public DateTime? arzo_FechaCreacion { get; set; }
        public int? arzo_UserModificacion { get; set; }
        public DateTime? arzo_FechaModificacion { get; set; }
        public bool? arzo_Estado { get; set; }

        public virtual tbUsuarios arzo_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios arzo_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbAnimales> tbAnimales { get; set; }
    }
}