// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
        }

        public string dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public int? dept_UserCreacion { get; set; }
        public DateTime? dept_FechaCreacion { get; set; }
        public int? dept_UserModificacion { get; set; }
        public DateTime? dept_FechaModificacion { get; set; }
        public bool? dept_Estado { get; set; }

        public virtual tbUsuarios dept_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios dept_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}