// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int empl_Id { get; set; }
        public string empl_Nombre { get; set; }
        public string empl_Apellido { get; set; }
        public string empl_Identidad { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public string empl_Direccion { get; set; }
        public string empl_Sexo { get; set; }
        public string empl_Telefono { get; set; }
        public int estc_Id { get; set; }
        public int carg_Id { get; set; }
        public string muni_Id { get; set; }
        public int? empl_UserCreacion { get; set; }
        public DateTime? empl_FechaCreacion { get; set; }
        public int? empl_UserModificacion { get; set; }
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }

        public virtual tbCargos carg { get; set; }
        public virtual tbUsuarios empl_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios empl_UserModificacionNavigation { get; set; }
        public virtual tbEstadosCiviles estc { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}