// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbEspecies
    {
        public tbEspecies()
        {
            tbRazas = new HashSet<tbRazas>();
        }

        public int espe_Id { get; set; }
        public string espe_Descripcion { get; set; }
        public int? espe_UserCreacion { get; set; }
        public DateTime? espe_FechaCreacion { get; set; }
        public int? espe_UserModificacion { get; set; }
        public DateTime? espe_FechaModificacion { get; set; }
        public bool? espe_Estado { get; set; }

        public virtual tbUsuarios espe_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios espe_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbRazas> tbRazas { get; set; }
    }
}