// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbFacturas
    {
        public tbFacturas()
        {
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
        }

        public int fact_Id { get; set; }
        public int empl_Id { get; set; }
        public int visi_Id { get; set; }

        [NotMapped]
        public string visi_Nombres { get; set; }

        [NotMapped]
        public string visi_RTN { get; set; }

        [NotMapped]
        public string visi_Sexo { get; set; }

       
        [NotMapped]
        public string empl_Nombre { get; set; }

        [NotMapped]
        public string tick_Descripcion { get; set; }

        [NotMapped]
        public string tick_Precio { get; set; }

        [NotMapped]
        public string fade_Cantidad { get; set; }

        [NotMapped]
        public string fade_Total { get; set; }


        [NotMapped]
        public string Ticket_Zoologico { get; set; }


        [NotMapped]
        public string Ticket_JardinBotanico { get; set; }

        [NotMapped]
        public string meto_Descripcion { get; set; }






        public int meto_Id { get; set; }
        public DateTime fact_Fecha { get; set; }
        public int? fact_UserCreacion { get; set; }
        public DateTime? fact_FechaCreacion { get; set; }
        public int? fact_UserModificacion { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }
        public bool? fact_Estado { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios fact_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios fact_UserModificacionNavigation { get; set; }
        public virtual tbMetodosPago meto { get; set; }
        public virtual tbVisitantes visi { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
    }
}