// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int muni_Id { get; set; }
        public string muni_Descripcion { get; set; }
        public int dept_Id { get; set; }
        public int? muni_UserCreacion { get; set; }
        public DateTime? muni_FechaCreacion { get; set; }
        public int? muni_UserModificacion { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }
        public bool? muni_Estado { get; set; }

        public virtual tbDepartamentos dept { get; set; }
        public virtual tbUsuarios muni_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios muni_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}