// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbPantallas
    {
        public int pant_Id { get; set; }
        public string pant_Descripcion { get; set; }
        public int? pant_UserCreacion { get; set; }
        public DateTime? pant_FechaCreacion { get; set; }
        public int? pant_UserModificacion { get; set; }
        public DateTime? pant_FechaModificacion { get; set; }

        public virtual tbUsuarios pant_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios pant_UserModificacionNavigation { get; set; }
    }
}