// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbPlantas
    {
        public tbPlantas()
        {
            tbCuidadoPlanta = new HashSet<tbCuidadoPlanta>();
        }

        public int plan_Id { get; set; }
        public string plan_Codigo { get; set; }
        public int arbo_Id { get; set; }
        public int tipl_Id { get; set; }
        public int? plan_UserCreacion { get; set; }
        public DateTime? plan_FechaCreacion { get; set; }
        public int? plan_UserModificacion { get; set; }
        public DateTime? plan_FechaModificacion { get; set; }
        public bool? plan_Estado { get; set; }

        public virtual tbAreasBotanicas arbo { get; set; }
        public virtual tbUsuarios plan_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios plan_UserModificacionNavigation { get; set; }
        public virtual tbTiposPlantas tipl { get; set; }
        public virtual ICollection<tbCuidadoPlanta> tbCuidadoPlanta { get; set; }
    }
}