// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbRazas
    {
        public tbRazas()
        {
            tbAnimales = new HashSet<tbAnimales>();
        }

        public int raza_Id { get; set; }
        public string raza_Descripcion { get; set; }
        public string raza_NombreCientifico { get; set; }
        public int rein_Id { get; set; }
        public int habi_Id { get; set; }
        public int espe_Id { get; set; }
        public int? raza_UserCreacion { get; set; }
        public DateTime? raza_FechaCreacion { get; set; }
        public int? raza_UserModificacion { get; set; }
        public DateTime? raza_FechaModificacion { get; set; }
        public bool? raza_Estado { get; set; }

        public virtual tbEspecies espe { get; set; }
        public virtual tbHabitat habi { get; set; }
        public virtual tbUsuarios raza_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios raza_UserModificacionNavigation { get; set; }
        public virtual tbReinos rein { get; set; }
        public virtual ICollection<tbAnimales> tbAnimales { get; set; }
    }
}