// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbReinos
    {
        public tbReinos()
        {
            tbAnimales = new HashSet<tbAnimales>();
            tbPlantas = new HashSet<tbPlantas>();
        }

        public int rein_Id { get; set; }
        public string rein_Descripcion { get; set; }
        public int? rein_UserCreacion { get; set; }
        public DateTime? rein_FechaCreacion { get; set; }
        public int? rein_UserModificacion { get; set; }
        public DateTime? rein_FechaModificacion { get; set; }
        public bool? rein_Estado { get; set; }

        public virtual tbUsuarios rein_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios rein_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbAnimales> tbAnimales { get; set; }
        public virtual ICollection<tbPlantas> tbPlantas { get; set; }
    }
}