// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbRolesPantallas
    {
        public int ropa_Id { get; set; }
        public int role_Id { get; set; }
        public int pant_Id { get; set; }
        public int? ropa_UserCreacion { get; set; }
        public DateTime? ropa_FechaCreacion { get; set; }
        public int? ropa_UserModificacion { get; set; }
        public DateTime? ropa_FechaModificacion { get; set; }

        public virtual tbUsuarios ropa_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios ropa_UserModificacionNavigation { get; set; }
    }
}