// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbTiposMantenimientos
    {
        public tbTiposMantenimientos()
        {
            tbMantenimientos = new HashSet<tbMantenimientos>();
        }

        public int tima_Id { get; set; }
        public string tima_Descripcion { get; set; }
        public int? tima_UserCreacion { get; set; }
        public DateTime? tima_FechaCreacion { get; set; }
        public int? tima_UserModificacion { get; set; }
        public DateTime? tima_FechaModificacion { get; set; }
        public bool? tima_Estado { get; set; }

        public virtual tbUsuarios tima_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios tima_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbMantenimientos> tbMantenimientos { get; set; }
    }
}