// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_UserCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusua_UserModificacionNavigation = new HashSet<tbUsuarios>();
            tbAlimentacionalim_UserCreacionNavigation = new HashSet<tbAlimentacion>();
            tbAlimentacionalim_UserModificacionNavigation = new HashSet<tbAlimentacion>();
            tbAnimalesanim_UserCreacionNavigation = new HashSet<tbAnimales>();
            tbAnimalesanim_UserModificacionNavigation = new HashSet<tbAnimales>();
            tbAreasBotanicasarbo_UserCreacionNavigation = new HashSet<tbAreasBotanicas>();
            tbAreasBotanicasarbo_UserModificacionNavigation = new HashSet<tbAreasBotanicas>();
            tbAreasZoologicoarzo_UserCreacionNavigation = new HashSet<tbAreasZoologico>();
            tbAreasZoologicoarzo_UserModificacionNavigation = new HashSet<tbAreasZoologico>();
            tbCargoscarg_UserCreacionNavigation = new HashSet<tbCargos>();
            tbCargoscarg_UserModificacionNavigation = new HashSet<tbCargos>();
            tbCuidadoscuid_UserCreacionNavigation = new HashSet<tbCuidados>();
            tbCuidadoscuid_UserModificacionNavigation = new HashSet<tbCuidados>();
            tbDepartamentosdept_UserCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdept_UserModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosempl_UserCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempl_UserModificacionNavigation = new HashSet<tbEmpleados>();
            tbEspeciesespe_UserCreacionNavigation = new HashSet<tbEspecies>();
            tbEspeciesespe_UserModificacionNavigation = new HashSet<tbEspecies>();
            tbEstadosCivilesestc_UserCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesestc_UserModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbFacturasDetallesfade_UserCreacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasDetallesfade_UserModificacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasfact_UserCreacionNavigation = new HashSet<tbFacturas>();
            tbFacturasfact_UserModificacionNavigation = new HashSet<tbFacturas>();
            tbHabitathabi_UserCreacionNavigation = new HashSet<tbHabitat>();
            tbHabitathabi_UserModificacionNavigation = new HashSet<tbHabitat>();
            tbMantenimientoAnimalmaan_UserCreacionNavigation = new HashSet<tbMantenimientoAnimal>();
            tbMantenimientoAnimalmaan_UserModificacionNavigation = new HashSet<tbMantenimientoAnimal>();
            tbMantenimientosmant_UserCreacionNavigation = new HashSet<tbMantenimientos>();
            tbMantenimientosmant_UserModificacionNavigation = new HashSet<tbMantenimientos>();
            tbMetodosPagometo_UserCreacionNavigation = new HashSet<tbMetodosPago>();
            tbMetodosPagometo_UserModificacionNavigation = new HashSet<tbMetodosPago>();
            tbMunicipiosmuni_UserCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UserModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallaspant_UserCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallaspant_UserModificacionNavigation = new HashSet<tbPantallas>();
            tbPlantasplan_UserCreacionNavigation = new HashSet<tbPlantas>();
            tbPlantasplan_UserModificacionNavigation = new HashSet<tbPlantas>();
            tbRolesPantallasropa_UserCreacionNavigation = new HashSet<tbRolesPantallas>();
            tbRolesPantallasropa_UserModificacionNavigation = new HashSet<tbRolesPantallas>();
            tbRolesrole_UserCreacionNavigation = new HashSet<tbRoles>();
            tbRolesrole_UserModificacionNavigation = new HashSet<tbRoles>();
            tbTicketstick_UserCreacionNavigation = new HashSet<tbTickets>();
            tbTicketstick_UserModificacionNavigation = new HashSet<tbTickets>();
            tbTiposMantenimientostima_UserCreacionNavigation = new HashSet<tbTiposMantenimientos>();
            tbTiposMantenimientostima_UserModificacionNavigation = new HashSet<tbTiposMantenimientos>();
            tbVisitantesvisi_UserCreacionNavigation = new HashSet<tbVisitantes>();
            tbVisitantesvisi_UserModificacionNavigation = new HashSet<tbVisitantes>();
        }

        public int usua_Id { get; set; }
        public string usua_NombreUsuario { get; set; }
        public int empl_Id { get; set; }
        public string usua_Clave { get; set; }
        public int role_Id { get; set; }
        public bool usua_Admin { get; set; }
        public int? usua_UserCreacion { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UserModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }

        public virtual tbUsuarios usua_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbAlimentacion> tbAlimentacionalim_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbAlimentacion> tbAlimentacionalim_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbAnimales> tbAnimalesanim_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbAnimales> tbAnimalesanim_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbAreasBotanicas> tbAreasBotanicasarbo_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbAreasBotanicas> tbAreasBotanicasarbo_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbAreasZoologico> tbAreasZoologicoarzo_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbAreasZoologico> tbAreasZoologicoarzo_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbCuidados> tbCuidadoscuid_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbCuidados> tbCuidadoscuid_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbEspecies> tbEspeciesespe_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbEspecies> tbEspeciesespe_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestc_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestc_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfade_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfade_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbHabitat> tbHabitathabi_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbHabitat> tbHabitathabi_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbMantenimientoAnimal> tbMantenimientoAnimalmaan_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbMantenimientoAnimal> tbMantenimientoAnimalmaan_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbMantenimientos> tbMantenimientosmant_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbMantenimientos> tbMantenimientosmant_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbPlantas> tbPlantasplan_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbPlantas> tbPlantasplan_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbRolesPantallas> tbRolesPantallasropa_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbRolesPantallas> tbRolesPantallasropa_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbTickets> tbTicketstick_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbTickets> tbTicketstick_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbTiposMantenimientos> tbTiposMantenimientostima_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbTiposMantenimientos> tbTiposMantenimientostima_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbVisitantes> tbVisitantesvisi_UserCreacionNavigation { get; set; }
        public virtual ICollection<tbVisitantes> tbVisitantesvisi_UserModificacionNavigation { get; set; }
    }
}