// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_FacturasDetalle
    {
        public int fade_Id { get; set; }
        public int tick_Id { get; set; }
        public string tick_Descripcion { get; set; }
        public int fade_Cantidad { get; set; }
        public decimal fade_Total { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? fade_UserCreacion { get; set; }
        public DateTime? fade_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? fade_UserModificacion { get; set; }
        public DateTime? fade_FechaModificacion { get; set; }
        public bool? fade_Estado { get; set; }
    }
}