// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbMetodosPago
    {
        public int meto_Id { get; set; }
        public string meto_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? meto_UserCreacion { get; set; }
        public DateTime? meto_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? meto_UserModificacion { get; set; }
        public DateTime? meto_FechaModificacion { get; set; }
        public bool? meto_Estado { get; set; }
    }
}