// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbFacturas
    {
        public int fact_Id { get; set; }
        public int empl_Id { get; set; }
        public string empleado { get; set; }
        public int visi_Id { get; set; }
        public string visitante { get; set; }
        public int meto_Id { get; set; }
        public string meto_Descripcion { get; set; }
        public DateTime fact_Fecha { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? fact_UserCreacion { get; set; }
        public DateTime? fact_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? fact_UserModificacion { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }
        public bool? fact_Estado { get; set; }
    }
}