// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbTiposPlantas
    {
        public int tipl_Id { get; set; }
        public string tipl_NombreComun { get; set; }
        public string tipl_NombreCientifico { get; set; }
        public int rein_Id { get; set; }
        public string rein_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? tipl_UserCreacion { get; set; }
        public DateTime? tipl_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? tipl_UserModificacion { get; set; }
        public DateTime? tipl_FechaModificacion { get; set; }
        public bool? tipl_Estado { get; set; }
    }
}