// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbTickets
    {
        public int tick_Id { get; set; }
        public string tick_Descripcion { get; set; }
        public decimal tick_Precio { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? tick_UserCreacion { get; set; }
        public DateTime? tick_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? tick_UserModificacion { get; set; }
        public DateTime? tick_FechaModificacion { get; set; }
        public bool? tick_Estado { get; set; }
    }
}