// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbMunicipios
    {
        public string muni_Id { get; set; }
        public string muni_Descripcion { get; set; }
        public string dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? muni_UserCreacion { get; set; }
        public DateTime? muni_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? muni_UserModificacion { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }
        public bool? muni_Estado { get; set; }
    }
}