// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbCargos
    {
        public int carg_Id { get; set; }
        public string carg_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? carg_UserCreacion { get; set; }
        public DateTime? carg_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? carg_UserModificacion { get; set; }
        public DateTime? carg_FechaModificacion { get; set; }
        public bool? carg_Estado { get; set; }
    }
}