// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbAreasBotanicas
    {
        public int arbo_Id { get; set; }
        public string arbo_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? arbo_UserCreacion { get; set; }
        public DateTime? arbo_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? arbo_UserModificacion { get; set; }
        public DateTime? arbo_FechaModificacion { get; set; }
        public bool? arbo_Estado { get; set; }
    }
}