// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbCuidados
    {
        public int cuid_Id { get; set; }
        public string cuid_Descripcion { get; set; }
        public string cuid_Frecuencia { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? cuid_UserCreacion { get; set; }
        public DateTime? cuid_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? cuid_UserModificacion { get; set; }
        public DateTime? cuid_FechaModificacion { get; set; }
        public bool? cuid_Estado { get; set; }
    }
}