// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbAnimales
    {
        public int anim_Id { get; set; }
        public string anim_Codigo { get; set; }
        public string anim_Nombre { get; set; }
        public int raza_Id { get; set; }
        public string raza_Descripcion { get; set; }
        public int habi_Id { get; set; }
        public string habi_Descripcion { get; set; }
        public int rein_Id { get; set; }
        public string rein_Descripcion { get; set; }
        public int arzo_Id { get; set; }
        public string arzo_Descripcion { get; set; }
        public int alim_Id { get; set; }
        public string alim_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? anim_UserCreacion { get; set; }
        public DateTime? anim_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? anim_UserModificacion { get; set; }
        public DateTime? anim_FechaModificacion { get; set; }
        public bool? anim_Estado { get; set; }
    }
}