// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbVisitantes
    {
        public int visi_Id { get; set; }
        public string visi_NombreCompleto { get; set; }
        public string visi_Nombres { get; set; }
        public string visi_Apellido { get; set; }

        public string visi_RTN { get; set; }
        public string visi_Sexo { get; set; }
        public string visi_Sexos { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? visi_UserCreacion { get; set; }
        public DateTime? visi_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? visi_UserModificacion { get; set; }
        public DateTime? visi_FechaModificacion { get; set; }
        public bool? visi_Estado { get; set; }
    }
}