// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbAreasZoologico
    {
        public int arzo_Id { get; set; }
        public string arzo_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? arzo_UserCreacion { get; set; }
        public DateTime? arzo_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? arzo_UserModificacion { get; set; }
        public DateTime? arzo_FechaModificacion { get; set; }
        public bool? arzo_Estado { get; set; }
    }
}