// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbDepartamentos
    {
        public string dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? dept_UserCreacion { get; set; }
        public DateTime? dept_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? dept_UserModificacion { get; set; }
        public DateTime? dept_FechaModificacion { get; set; }
        public bool? dept_Estado { get; set; }
    }
}