// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbUsuarios
    {
        public int usua_Id { get; set; }
        public string usua_NombreUsuario { get; set; }
        public int empl_Id { get; set; }
        public string empl_Nombre { get; set; }
        public string usua_Clave { get; set; }
        public int role_Id { get; set; }
        public string role_Descripcion { get; set; }
        public bool usua_Admin { get; set; }
        public string usua_EsAdmin { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? usua_UserCreacion { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? usua_UserModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }
    }
}