// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbVisitantes
    {
        public int visi_Id { get; set; }
        public string visi_Nombre { get; set; }
        public string visi_Identidad { get; set; }
        public DateTime visi_FechaNacimiento { get; set; }
        public string visi_Direccion { get; set; }
        public string visi_Sexo { get; set; }
        public string visi_Telefono { get; set; }
        public int estc_Id { get; set; }
        public string estc_Descripcion { get; set; }
        public int muni_Id { get; set; }
        public string muni_Descripcion { get; set; }
        public int dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? visi_UserCreacion { get; set; }
        public DateTime? visi_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? visi_UserModificacion { get; set; }
        public DateTime? visi_FechaModificacion { get; set; }
        public bool? visi_Estado { get; set; }
    }
}