// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbEmpleados
    {
        public int empl_Id { get; set; }
        public string empl_Nombre { get; set; }
        public string empl_Apellido { get; set; }
        public string empl_Identidad { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public string empl_Direccion { get; set; }
        public string empl_Sexo { get; set; }
        public string empl_Sexos { get; set; }
        public string empl_Telefono { get; set; }
        public int estc_Id { get; set; }
        public string estc_Descripcion { get; set; }
        public int carg_Id { get; set; }
        public string carg_Descripcion { get; set; }
        public int muni_Id { get; set; }
        public string muni_Descripcion { get; set; }
        public int dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? empl_UserCreacion { get; set; }
        public DateTime? empl_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? empl_UserModificacion { get; set; }
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }
    }
}