// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Lancetilla.Entities.Entities
{
    public partial class VW_tbEspecies
    {
        public int espe_Id { get; set; }
        public string espe_Descripcion { get; set; }
        public string usua_UserCreaNombre { get; set; }
        public int? espe_UserCreacion { get; set; }
        public DateTime? espe_FechaCreacion { get; set; }
        public string usua_UserModiNombre { get; set; }
        public int? espe_UserModificacion { get; set; }
        public DateTime? espe_FechaModificacion { get; set; }
        public bool? espe_Estado { get; set; }
    }
}